server:
  name: deposition-backend
  port: 80

logging:
  level:
    org:
      springframework:
        web: DEBUG

gwas-deposition:
  auth:
    enabled: false

gwas-sumstats-service:
  enabled: false
  url: https://gwas-sumstats-service
  endpoints:
    sum-stats: /v1/sum-stats
  callback-schedule:
    enabled: false
    freq: 0 */1 * * * ?

gwas-template-service:
  enabled: false
  url: https://gwas-template-service
  endpoints:
    template-schema: /v1/template-schema

spring:
  profiles:
    active: dev
